import fs from "fs";

const c = fs.readFileSync("src/data/content.ts", "utf-8");
const faqDecl = c.indexOf("export const faqItems");
const blogClose = c.lastIndexOf("];", faqDecl);

const newBlogs = `
  {
    slug: "how-indie-perfumers-produce-glass-bottles",
    title: { en: "How on Earth Do Indie Perfumers Produce Glass Bottles? A Realistic Guide", kr: "인디 퍼퓨머가 유리병을 만드는 방법", jp: "インディー香水ブランドがガラスボトルを作る方法", tw: "獨立香水品牌如何生產玻璃瓶" },
    excerpt: { en: "Reddit's r/fragrance asks the question every aspiring perfumer hits: how do I get 200 custom glass bottles without a 10,000 MOQ? Here's the honest answer.", kr: "레딧 r/fragrance의 모든 향수 창업자가 묻는 질문.", jp: "Reddit r/fragranceのすべての香水創業者が問う質問。", tw: "Reddit r/fragrance 每個香水創業者都會問的問題。" },
    body: { en: "A thread on r/fragrance titled 'How on earth do new brands produce bottles?' has hundreds of comments from aspiring perfumers stuck at the same wall: fragrance manufacturers quote 10,000-unit MOQs for custom glass molds, but a new brand needs 200-500 units to test the market. One Dubai-based manufacturer even commented on the thread offering 10K minimum for new molds — technically honest, practically useless for a startup.\n\nThe reality is that glass perfume bottles sit on a spectrum of options, and the best path depends on your launch stage. At the very start (0-500 units): use stock vials and roll-on bottles from packaging distributors. A 5ml roll-on amber vial costs $0.15-0.30 at 200 units. Your first customers care about the juice, not the bottle. This is how most successful indie perfumers (including several featured in r/Indiemakeupandmore) actually launch.\n\nAt the next stage (500-5,000 units): you can order stock glass dropper bottles or euro-style perfume vials with custom labels. Our amber vial droppers start at 5,000 pcs for $0.35-0.55 per unit with silk-screen branding. You get a professional-looking product without paying for custom tooling. The label does the branding work; the glass provides the premium weight and UV protection that plastic can't match.\n\nCustom molds become viable at 10,000+ units: tooling runs $3,000-15,000 depending on complexity, plus a per-unit premium of 15-25% over stock molds. At this volume, brands typically have confirmed wholesale orders or a retailer distribution agreement. The r/fragrance thread's best advice, echoed by every veteran perfumer: don't commission a custom mold until a distributor has signed a purchase order. The perfume market is brutal, and a beautiful empty bottle doesn't sell itself — your juice and your story do.", kr: "本文", jp: "本文", tw: "本文" },
    date: "2026-08-05", readMinutes: 6, category: "guide",
    keywords: ["indie perfume bottle manufacturer", "custom glass perfume bottle MOQ", "how to make perfume bottles small batch", "perfume vial wholesale glass", "fragrance brand launch packaging"],
  },
  {
    slug: "glass-vs-plastic-sunscreen-packaging",
    title: { en: "Can Sunscreen Go in Glass? A 2026 Packaging Reality Check", kr: "선크림은 유리에 담길 수 있나? 2026 포장 현실 점검", jp: "日焼け止めはガラスに入れられる？2026年パッケージング検証", tw: "防曬乳可以裝在玻璃裡嗎？2026 包裝現實檢驗" },
    excerpt: { en: "Reddit's r/EuroSkincare is asking for sunscreen in non-plastic packaging. The answer is more complicated than you'd think — UV protection is only half the story.", kr: "레딧 r/EuroSkincare: 플라스틱 없는 선크림 찾기.", jp: "Reddit r/EuroSkincare：プラスチック不使用の日焼け止め。", tw: "Reddit r/EuroSkincare：尋找非塑膠防曬包裝。" },
    body: { en: "A thread on r/EuroSkincare titled 'Looking for sunscreen in non-plastic packaging' captures a growing consumer demand that most cosmetic brands are ignoring. The comments are full of people frustrated that every sunscreen comes in a plastic tube or bottle. But here's why glass sunscreen packaging is genuinely difficult — and why it's a real opportunity for brands who get it right.\n\nThe first problem is chemistry, not packaging. Chemical UV filters (avobenzone, octocrylene, oxybenzone) are notoriously sensitive to UV radiation themselves. Avobenzone degrades by up to 36% after just one hour of direct sunlight — even in an opaque container, because heat accelerates the degradation. Amber glass provides excellent UV protection (blocks ~98% of UV-A and UV-B), but sunscreen formulas stored in amber glass still need antioxidants and photostabilizers in the formulation itself. The glass can't do all the work.\n\nThe second problem is formulation compatibility. Many sunscreen actives are oil-soluble and slightly acidic. Type III soda-lime glass is generally compatible, but mineral sunscreens containing zinc oxide or titanium dioxide can settle and clump in a narrow-neck glass bottle, requiring constant shaking. This is why most mineral sunscreens use wide-mouth jars or airless pumps. If you want glass packaging for a mineral sunscreen, a wide-mouth glass jar with a spatula is the practical answer.\n\nThe third problem is real but solvable: glass is heavy. A 50ml glass sunscreen bottle weighs 90-120g versus 20g for plastic. Shipping costs rise 15-20% for a case of 12. For premium brands selling at $45+, the weight signals quality. For drugstore brands at $12, glass breaks the margin.\n\nWhere glass genuinely wins: UV protection, shelf perception, and refill potential. A mineral sunscreen in a 50g amber glass jar with a wooden lid photographs beautifully, reads as 'clean beauty,' and supports a refill pouch program. That's a positioning play, not a cost play — and in the premium sun-care niche, positioning is everything. If you're a brand considering glass sunscreen packaging, the winning formula is: mineral formulation + wide-mouth amber jar + refill system + a story about UV protection. That combination doesn't exist on most drugstore shelves yet — and it's exactly what r/EuroSkincare's consumers are searching for.", kr: "本文", jp: "本文", tw: "本文" },
    date: "2026-08-05", readMinutes: 7, category: "material",
    keywords: ["sunscreen glass packaging", "non plastic sunscreen bottle", "amber glass UV protection sunscreen", "mineral sunscreen jar glass", "clean beauty sunscreen packaging"],
  },`;

const result = c.slice(0, blogClose) + newBlogs + "\n];\n\n" + c.slice(blogClose + 2);
fs.writeFileSync("src/data/content.ts", result, "utf-8");
console.log((result.match(/slug: "/g) || []).length + " blog posts total");
